# specify the docker verion and then build the images and push them to ECR:
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Login to ECR
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 504857465313.dkr.ecr.us-east-2.amazonaws.com

      # - echo Build client and backend docker images for testing...
      # - docker build -t jeezhou/clientfrontend ./client
      # - docker build -t jeezhou/nginx ./nginx
  build:
    commands:
      # pull the images here and push to ecr here?
      - echo logged in and build client frontend and nginx
      - docker build -t 504857465313.dkr.ecr.us-east-2.amazonaws.com/clientimage ./client
      - docker build -t 504857465313.dkr.ecr.us-east-2.amazonaws.com/nginximage ./nginx
  post_build:
    commands:
      - echo Pushing the client image to ECR
      - docker push 504857465313.dkr.ecr.us-east-2.amazonaws.com/clientimage:latest
      - docker push 504857465313.dkr.ecr.us-east-2.amazonaws.com/nginximage:latest
      - echo Constructing the imageDefintion file for deployment
      - printf '[{"name":"client", "imageUri":"504857465313.dkr.ecr.us-east-2.amazonaws.com/clientimage:latest"}, {"name":"nginx", "imageUri":"504857465313.dkr.ecr.us-east-2.amazonaws.com/nginximage:latest"}]' > imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json
      # - docker build -t jeezhou/nginx ./nginx
  #     - echo Build started on `date`
  #     # Run tests with built Docker images
  #     - echo Run react tests...
  #     - docker run -e CI=true lukondefmwila/react-test
  #     - echo Run nodejs tests...
  #     - docker run -e CI=true lukondefmwila/nodejs-test
      # Scan Docker image with Snyk
      ## Client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker lukondefmwila/react-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker lukondefmwila/react-test:latest --file=./client/Dockerfile.dev
      ## Backend
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker lukondefmwila/nodejs-test:latest --file=./backend/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker lukondefmwila/nodejs-test:latest --file=./backend/Dockerfile.dev
      # Build the Docker images
      # - echo Building the production Docker image...
      # - docker build -t lukondefmwila/dkr-multicontainer-app-client ./client
      # - docker build -t lukondefmwila/dkr-multicontainer-app-backend ./backend
      # - docker build -t lukondefmwila/dkr-multicontainer-app-nginx ./nginx
      # # Log in to the Docker CLI
      # - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # post_build:
  #   commands:
  #     # Take these images and push them to Docker hub
  #     - echo Pushing the Docker images...
  #     - docker push lukondefmwila/dkr-multicontainer-app-client
  #     - docker push lukondefmwila/dkr-multicontainer-app-backend
  #     - docker push lukondefmwila/dkr-multicontainer-app-nginx